module.exports = {
  "ar": "ar-AR_BroadbandModel",
  "pt": "pt-BR_BroadbandModel",
  "zh": "zh-CN_BroadbandModel",
  "nl": "nl-NL_BroadbandModel",
  "en-au": "en-AU_BroadbandModel",
  "en-gb": "en-GB_BroadbandModel",
  "en": "en-US_BroadbandModel",
  "fr": "fr-FR_BroadbandModel",
  "fr-ca": "fr-CA_BroadbandModel",
  "de": "de-DE_BroadbandModel",
  "it": "it-IT_BroadbandModel",
  "ja": "ja-JP_BroadbandModel",
  "ko": "ko-KR_BroadbandModel",
  "es-ar": "es-AR_BroadbandModel",
  "es-es": "es-ES_BroadbandModel",
  "es-cl": "es-CL_BroadbandModel",
  "es-co": "es-CO_BroadbandModel",
  "es": "es-MX_BroadbandModel",
  "es-pe": "es-PE_BroadbandModel"
};
